import React from "react";

const columns = [
  {name: "NOMBRE", uid: "name", sortable: true},
  {name: "IDIOMA", uid: "language", sortable: true},
  {name: "DURACION", uid: "duration", sortable: true},
  {name: "GÉNERO", uid: "type", sortable: true},
  {name: "CLASIFICACION", uid: "classification", sortable: true},
  {name: "HORA", uid: "time", sortable: true},
  {name: "SUCURSAL", uid: "sucursal", sortable: true},
];

const statusOptions = [
  {name: "Colectivo", uid: "Colectivo"},
  {name: "Norte", uid: "Norte"},
  {name: "Klub", uid: "Klub"},
];

const languageOptions = [
    {name: "Español", uid: "Español"},
    {name: "Inglés", uid: "Inglés"},
    {name: "Subtitulada", uid: "Subtitulada"},
  ];

const typeOptions = [
  {name: "Infantil", uid: "Infantil"},
  {name: "Aventura", uid: "Aventura"},
  {name: "Acción", uid: "Acción"},
  {name: "Suspenso", uid: "Suspenso"},
  {name: "Comedia", uid: "Comedia"},
  {name: "Drama", uid: "Drama"},
  {name: "Terror", uid: "Terror"},
  {name: "Ciencia Ficción", uid: "Ciencia Ficción"},
  {name: "Romance", uid: "Romance"},
];

const users = [
  {
    id: "1",
    name: "PAW Patrol: The Mighty Movie",
    language: "Inglés",
    duration: "93 min",
    type: "Infantil",
    classification: "AA",
    time: "12:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/23_08/2023/15837338/l_paw-patrol-the-mighty-movie-movie-poster_e31ad488.jpg",
    description: "Un meteorito mágico aterriza en Adventure City y le da a los cachorros de PAW Patrol superpoderes, transformándolos en The Mighty Pups",
  },
  {
    id: "2",
    name: "Saw X",
    language: "Inglés",
    duration: "118 min",
    type: "Suspenso",
    classification: "C",
    time: "24:00",
    sucursal: "Norte",
    avatar: "https://posters.movieposterdb.com/23_10/2023/21807222/l_saw-x-movie-poster_3f1c61e0.jpg",
    description: "Un enfermo y desesperado John viaja a México para un procedimiento médico arriesgado y experimental con la esperanza de una cura milagrosa para su cáncer solo para descubrir que toda la operación es una estafa para estafar a los más vulnerables.",
  },
  {
    id: "3",
    name: "Barbie",
    language: "Español",
    duration: "125 min",
    type: "Comedia",
    classification: "B",
    time: "10:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/23_01/2023/1517268/l_barbie-movie-poster_32296e92.jpg",
    description: "Barbie sufre una crisis que la lleva a cuestionar su mundo y su existencia.",
  },
  {
    id: "4",
    name: "Oppenheimer",
    language: "Español",
    duration: "183 min",
    type: "Drama",
    classification: "B15",
    time: "12:00",
    sucursal: "Klub",
    avatar: "https://posters.movieposterdb.com/23_06/2023/15398776/l_oppenheimer-movie-poster_a83f1cbb.jpg",
    description: "La historia del científico estadounidense J. Robert Oppenheimer y su papel en el desarrollo de la bomba atómica.",
  },
  {
    id: "5",
    name: "Oppenheimer",
    language: "Subtitulado",
    duration: "183 min",
    type: "Drama",
    classification: "B15",
    time: "13:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/23_06/2023/15398776/l_oppenheimer-movie-poster_a83f1cbb.jpg",
    description: "La historia del científico estadounidense J. Robert Oppenheimer y su papel en el desarrollo de la bomba atómica.",
  },
  {
    id: "6",
    name: "La monja 2",
    language: "Español",
    duration: "110 min",
    type: "Terror",
    classification: "B15",
    time: "13:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/23_07/0/10160976/l_the-nun-2-movie-poster_3661310b.jpg",
    description: "Un sacerdote es asesinado. Un mal se está extendiendo. La secuela del gran éxito mundial sigue a la Hermana Irene cuando una vez más se encuentra cara a cara con Valak, la monja demonio.",
  },
  {
    id: "7",
    name: "Cacería en Venecia",
    language: "Español",
    duration: "103 min",
    type: "Suspenso",
    classification: "B",
    time: "20:00",
    sucursal: "Norte",
    avatar: "https://posters.movieposterdb.com/23_08/2023/22687790/l_a-haunting-in-venice-movie-poster_cbfa5e77.jpeg",
    description: "En la Venecia posterior a la Segunda Guerra Mundial, Poirot, ahora retirado y viviendo en su propio exilio, asiste a regañadientes a una sesión de espiritismo. Pero cuando uno de los invitados es asesinado, depende del ex detective descubrir una vez más al asesino.",
  },
  {
    id: "8",
    name: "Resistencia",
    language: "Español",
    duration: "133 min",
    type: "Ciencia Ficción",
    classification: "B",
    time: "20:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/23_09/2023/11858890/l_the-creator-movie-poster_d3ae1297.jpg",
    description: "Descrito como un thriller post-apocalíptico que involucra un futuro impactado por una guerra entre humanos e IA.",
  },
  {
    id: "9",
    name: "The Expendables 4",
    language: "Inglés",
    duration: "103 min",
    type: "Acción",
    classification: "B15",
    time: "17:00",
    sucursal: "Klub",
    avatar: "https://posters.movieposterdb.com/23_06/2023/3291150/l_expend4bles-movie-poster_0c5a0270.jpg",
    description: "Los mercenarios se enfrentarán a: un traficante de armas que comanda el poder de un ejército privado masivo.",
  },
  {
    id: "10",
    name: "Gran Turismo",
    language: "Subtitulado",
    duration: "134 min",
    type: "Acción",
    classification: "B",
    time: "16:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/23_08/2023/4495098/l_gran-turismo-movie-poster_0d619238.jpg",
    description: "La historia definitiva de cumplimiento de deseos de un jugador adolescente de Gran Turismo cuyas habilidades de juego ganaron una serie de competiciones de Nissan para convertirse en un verdadero piloto de carreras profesional. Basado en una historia real",
  },
  {
    id: "11",
    name: "Super Mario Bros.",
    language: "Inglés",
    duration: "92 min",
    type: "Comedia",
    classification: "AA",
    time: "11:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/23_02/2023/6718170/l_untitled-super-mario-project-movie-poster_c004ecb2.jpg",
    description: "La historia de The Super Mario Bros en su viaje por el Reino Champiñón.",
  },
  {
    id: "12",
    name: "Endless",
    language: "Inglés",
    duration: "94 min",
    type: "Romance",
    classification: "B",
    time: "16:00",
    sucursal: "Norte",
    avatar: "https://posters.movieposterdb.com/20_06/2020/5723282/l_5723282_b3cc95f3.jpg",
    description: "Cuando los graduados de secundaria locamente enamorados Riley (Alexandra Shipp) y Chris (Nicholas Hamilton) se separan por un trágico accidente automovilístico, Riley se culpa a sí misma por la muerte de su novio mientras.",
  },
  {
    id: "13",
    name: "Endless",
    language: "Subtitulado",
    duration: "94 min",
    type: "Romance",
    classification: "B",
    time: "18:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/20_06/2020/5723282/l_5723282_b3cc95f3.jpg",
    description: "Cuando los graduados de secundaria locamente enamorados Riley (Alexandra Shipp) y Chris (Nicholas Hamilton) se separan por un trágico accidente automovilístico, Riley se culpa a sí misma por la muerte de su novio mientras.",
  },
  {
    id: "14",
    name: "Gran Turismo",
    language: "Español",
    duration: "134 min",
    type: "Acción",
    classification: "B",
    time: "19:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/23_08/2023/4495098/l_gran-turismo-movie-poster_0d619238.jpg",
    description: "La historia definitiva de cumplimiento de deseos de un jugador adolescente de Gran Turismo cuyas habilidades de juego ganaron una serie de competiciones de Nissan para convertirse en un verdadero piloto de carreras profesional. Basado en una historia real",
  },
  {
    id: "15",
    name: "Saw X",
    language: "Español",
    duration: "118 min",
    type: "Suspenso",
    classification: "C",
    time: "23:00",
    sucursal: "Norte",
    avatar: "https://posters.movieposterdb.com/23_10/2023/21807222/l_saw-x-movie-poster_3f1c61e0.jpg",
    description: "Un enfermo y desesperado John viaja a México para un procedimiento médico arriesgado y experimental con la esperanza de una cura milagrosa para su cáncer solo para descubrir que toda la operación es una estafa para estafar a los más vulnerables.",
  },
  {
    id: "16",
    name: "Super Mario Bros.",
    language: "Subtitulado",
    duration: "92 min",
    type: "Comedia",
    classification: "AA",
    time: "10:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/23_02/2023/6718170/l_untitled-super-mario-project-movie-poster_c004ecb2.jpg",
    description: "La historia de The Super Mario Bros en su viaje por el Reino Champiñón.",
  },
  {
    id: "17",
    name: "The Expendables 4",
    language: "Subtitulado",
    duration: "103 min",
    type: "Acción",
    classification: "B15",
    time: "17:00",
    sucursal: "Colectivo",
    avatar: "https://posters.movieposterdb.com/23_06/2023/3291150/l_expend4bles-movie-poster_0c5a0270.jpg",
    description: "Los mercenarios se enfrentarán a: un traficante de armas que comanda el poder de un ejército privado masivo.",
  },
  {
    id: "18",
    name: "Los Indestructibles 4",
    language: "Español",
    duration: "103 min",
    type: "Acción",
    classification: "B15",
    time: "20:00",
    sucursal: "Norte",
    avatar: "https://posters.movieposterdb.com/23_06/2023/3291150/l_expend4bles-movie-poster_0c5a0270.jpg",
    description: "Los mercenarios se enfrentarán a: un traficante de armas que comanda el poder de un ejército privado masivo.",
  },
  {
    id: "19",
    name: "The Nun 2",
    language: "Inglés",
    duration: "110 min",
    type: "Terror",
    classification: "B15",
    time: "13:00",
    sucursal: "Norte",
    avatar: "https://posters.movieposterdb.com/23_07/0/10160976/l_the-nun-2-movie-poster_3661310b.jpg",
    description: "Un sacerdote es asesinado. Un mal se está extendiendo. La secuela del gran éxito mundial sigue a la Hermana Irene cuando una vez más se encuentra cara a cara con Valak, la monja demonio.",
  },
  {
    id: "20",
    name: "La monja 2",
    language: "Español",
    duration: "110 min",
    type: "Terror",
    classification: "B15",
    time: "13:00",
    sucursal: "Klub",
    avatar: "https://posters.movieposterdb.com/23_07/0/10160976/l_the-nun-2-movie-poster_3661310b.jpg",
    description: "Un sacerdote es asesinado. Un mal se está extendiendo. La secuela del gran éxito mundial sigue a la Hermana Irene cuando una vez más se encuentra cara a cara con Valak, la monja demonio.",
  },
];

export {columns, users, statusOptions, languageOptions, typeOptions};
